steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/your-project-id/your-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/your-project-id/your-app']
images: ['gcr.io/your-project-id/your-app']
name: GCP Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcloud builds submit --project=your-project-id
